name: Static Analysis

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
      
    steps:
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: List the working directory of the VM
      run: |
        pwd
    - uses: actions/checkout@v3
    - name: 
      uses: docker://hadolint/hadolint:v2.8.0
      with:
        python-version: ${{ matrix.python-version }}
    - name:
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile