name: Static Analysis

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
      
    steps:
    - uses: actions/checkout@v3
    - name: Pulling Docker containers
      run: |
        docker pull hadolint/hadolint:v2.8.0
    - name: Linting Dockerfiles with Hadolint
      run: |
        docker run --rm -i hadolint/hadolint:v2.8.0 < Dockerfile
